### ISSUE TITLE
Support generating multiple file keys at once

### ISSUE THREAD

**Issue by vyasr** [rapidsai/dependency-file-generator#114]
We should pass `nargs` parameter to make the `--file-key` CLI arg support generating a file with multiple keys. That will make it much easier for us to create complete environments for cases like unisolated wheel builds where we need multiple sets of dependencies installed into the same environment.

**Comment by jameslamb** [comment]
I'm going to try this: https://github.com/rapidsai/cuspatial/pull/1473#issuecomment-2417769222
