### ISSUE TITLE
Fix Version Number for Releases

### ISSUE THREAD

**Issue by ajschmidt8** [rapidsai/dependency-file-generator#15]
Apparently `rapids-dependency-file-generator` always reports a version of `0.0.0` regardless of the release. That's likely due to the hardcoded string in the file below. We should update our CI release process to patch the string in that file before publishing a new release.

- https://github.com/rapidsai/dependency-file-generator/blob/main/src/rapids_dependency_file_generator/_version.py

**Comment by ajschmidt8** [comment]
@bdice, where are you experiencing this issue? I found [this code](https://github.com/rapidsai/dependency-file-generator/blob/7757e34a2e54a814320e4d3b44a34dab66499a9d/.github/workflows/build-test-publish.yaml#L28-L31) which seems to be patching the version in CI before a release and the release packages seem fine to me based on the screenshots below.

**command**: `docker run --rm --pull=always rapidsai/ci:cuda11.5.1-ubuntu20.04-py3.8 rapids-dependency-file-generator -h`

![image](https://user-images.githubusercontent.com/7400326/200078701-29151a58-d317-4a71-a991-11f53b778eb9.png)


**command**: `docker run --rm --pull=always rapidsai/ci:cuda11.5.1-ubuntu20.04-py3.8 python -c "import rapids_dependency_file_generator; print(rapids_dependency_file_generator._version.__version__)"`

![image](https://user-images.githubusercontent.com/7400326/200078868-55aaedff-d8ba-47fa-89ab-cb083bc8a961.png)

**Comment by bdice** [comment]
@ajschmidt8 I did a local `pip install -e` so it was just reading the files from my local repo. I’m not sure how to reconcile committing a new version number or git tag with the “release every commit” philosophy. Maybe it needs to read info from the git repo to know what commit it’s on? I think that is how versioneer works. No need to overengineer this but it is a mildly strange problem and makes it tough to know if I’m testing the right version locally.

**Comment by ajschmidt8** [comment]
@bdice, I have a few thoughts here.

Personally, I'm partial to keeping the current process of hardcoding `0.0.0` and patching it during the release process. This way, you can tell if you're using an actual release version (e.g. `0.0.25`) or a local development version via `pip install -e .`.


If you have strong feelings about keeping the version string in the `git` repo up-to-date, [semantic-release-git](https://github.com/semantic-release/git) can be used to push a release commit with the version string updated whenever a release occurs. If we do this, we might want to append some kind of `.post0` string to the version number to differentiate it from an actual release on PyPI.

**Comment by vyasr** [comment]
FWIW I ran into this as well pretty recently and had the same confusion. I agree that it's not a big issue though, just a minor annoyance when developing.
