### ISSUE TITLE
Initial feedback

### ISSUE THREAD

**Issue by vyasr** [rapidsai/dependency-file-generator#2]
I'm just using this issue to track some initial feedback that I have on the code in this repo. I will attempt to make PRs for some things that are obvious improvements and can clean up this list as I go, but this is a useful starting point for collecting various unrelated thoughts.
- pytorch is listed twice in the build list
- The supported set of matrix components and the way that they are mapped to the final file/env name is currently [an implementation detail](https://github.com/rapidsai/rapids-env-generator/blob/main/src/rapids_env_generator/rapids_env_generator.py#L66). That should be documented somewhere, as well as a process for extending the matrix if we need to add additional components.
- The `includes` subsection of the `envs` section is documented as "the names of the keys whose lists should be included in the final environment file". Where are these keys searched? Both the `specifics/$MATRIX` section and at the top level (so that a top-level `build` is found)? I think it would probably be cleaner if the top-level search was instead moved into a `generics` or `general` section to more directly parallel the `specifics` section. Alternatively, we could do something like `includes/$MATRIX/build` for matrix-specific build requirements, and `includes/build` for matrix-agnostic (aka generic) build requirements. Thoughts?
- Is there ever a case where we need separate channels for separate environments? For example, could we need `rapidsai` vs `rapisai-nightly`? If so, is that supported?
- I would recommend putting configuration information and constants like the default channels, the env name (e.g. the string `f"cuda-{cuda_version}-arch-{aarch}"`), etc into a single module where it's easy to look up and modify rather than integrating them directly into the code.

One bigger picture question, which I know that I have returned to a few times with @ajschmidt8 but I think is worth raising here since the generator offers some new potential solutions: how do we want to handle `requirements.txt` files for non-conda users? I was originally thinking that we'd need to maintain those requirements separately. However, looking at the generator, I'm wondering if we could simply introduce an extra section or two that corresponds to pip-specific requirements, use the same sort of merging logic, and then at the end use a separate file generator (not PyYAML) to write out a requirements.txt-compliant file?

**Comment by ajschmidt8** [comment]
> pytorch is listed twice in the build list

removed the duplicate. this was meant to demonstrate that it will be de-duped, but I don't think it was very clear in my examples.

> The supported set of matrix components and the way that they are mapped to the final file/env name is currently [an implementation detail](https://github.com/rapidsai/rapids-env-generator/blob/main/src/rapids_env_generator/rapids_env_generator.py#L66). That should be documented somewhere, as well as a process for extending the matrix if we need to add additional components.

I'll get that documented.

> The includes subsection of the envs section is documented as "the names of the keys whose lists should be included in the final environment file". Where are these keys searched? Both the specifics/$MATRIX section and at the top level (so that a top-level build is found)? I think it would probably be cleaner if the top-level search was instead moved into a generics or general section to more directly parallel the specifics section. Alternatively, we could do something like includes/$MATRIX/build for matrix-specific build requirements, and includes/build for matrix-agnostic (aka generic) build requirements. Thoughts?

based on our call yesterday, it seems it would be best to restructure things as we discussed.

> Is there ever a case where we need separate channels for separate environments? For example, could we need rapidsai vs rapisai-nightly? If so, is that supported?

I don't think we need to account for that use-case

> I would recommend putting configuration information and constants like the default channels, the env name (e.g. the string f"cuda-{cuda_version}-arch-{aarch}"), etc into a single module where it's easy to look up and modify rather than integrating them directly into the code.

Sounds like a good idea.

Based on your feedback here and our discussion yesterday, I'm going to continue iterating on our current setup to see if we can get this package into a more future-proof spot to support `requirements.txt` files also. We don't have to solve all the problems now, but having a good foundation from the start will help us add features in the future.

**Comment by vyasr** [comment]
I think these issues have mostly been addressed at this point. Closing in favor of new discussions based on the current state.
